# Default values for torch.cloud.
# This is a YAML-formatted file.

# Create a secret for the Docker registry
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=vekjja \
#   --docker-password=${GITHUB_PAT}

# Declare variables to be passed into your templates.
#  helm upgrade --install torch-cloud helm/app -f helm/app/values.yaml \
#    --namespace torch-cloud \
#    --create-namespace

# Bitnami PostgreSQL subchart (https://github.com/bitnami/charts/tree/main/bitnami/postgresql).
postgresql:
  enabled: true
  fullnameOverride: torch-cloud-psql

  image:
    pullPolicy: IfNotPresent
    debug: true

  auth:
    existingSecret: torch-cloud-env
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
    database: torch-cloud

  volumePermissions:
    enabled: true

  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: local-path

    resourcesPreset: none
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

image:
  repository: ghcr.io/vekjja/torch.cloud
  pullPolicy: Always
  tag: "development"

imagePullSecrets:
- name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

# This section builds out the srvice account 
# more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {} # fsGroup: 2000

securityContext: {}
  # capabilities:
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

externalSecret:
  enabled: true
  name: torch-cloud-env
  secretStoreName: gcp-secret-manager
  secretStoreKind: ClusterSecretStore
  remoteSecretName: torch-cloud-env
  refreshInterval: 1h

envFrom:
- secretRef:
    name: torch-cloud-env

env:
- name: NODE_ENV
  value: production

ingress:
  enabled: true
  className: "nginx"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: torch.cloud
    external-dns.alpha.kubernetes.io/target: "174.44.105.210"
    cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-production"
  hosts:
  - host: torch.cloud
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: torch.cloud-tls
    hosts:
    - torch.cloud

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

startupProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 9

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
